@host=127.0.0.1:5000
@apiKey=QsfrOkziZ67i1k2rPF5zFdYabzImnVuAOgN6uqKhTgl2eyizhU3anW4tV9FUbPuZ
@apiSecret=LCv7s60DmNBM0pQ2FUl8NCGo3QWxgYE6TMsh20ZVKKUS8RDHCZaPUMKargwrMsN5
@demoMode=true
@contectType=application/json
@token={{login.response.body.token}}
@symbol=ETHUSDT
@interval=1m

###

# @name login

POST http://{{host}}/login HTTP/1.1
Content-Type: {{contectType}}

{
    "key": "{{apiKey}}",
    "secret": "{{apiSecret}}"
}

###

# @name createWatchdog
POST http://{{host}}/watchdog HTTP/1.1
Content-Type: {{contectType}}
Authorization: Bearer {{token}}

[
    {
        "symbol": "ADAUSDT",
        "interval": "1h",
        "risk": 15.0,
        "commission": 0.1,
        "leverage": 1,
        "demo": {{demoMode}}
    }
]

###

DELETE http://{{host}}/watchdog/ADAUSDT/1h HTTP/1.1
Authorization: Bearer {{token}}

###
# @name createWatchdogs

POST http://{{host}}/watchdog HTTP/1.1
Content-Type: {{contectType}}
Authorization: Bearer {{token}}

[
    {
        "symbol": "BTCUSDT",
        "interval": "{{interval}}",
        "risk": 15.0,
        "commission": 0.1,
        "leverage": 1,
        "demo": {{demoMode}}
    },
    {
        "symbol": "ETHUSDT",
        "interval": "{{interval}}",
        "risk": 15.0,
        "commission": 0.1,
        "leverage": 1,
        "demo": {{demoMode}}
    },
    {
        "symbol": "BNBUSDT",
        "interval": "{{interval}}",
        "risk": 15.0,
        "commission": 0.1,
        "leverage": 1,
        "demo": {{demoMode}}
    },
    {
        "symbol": "NEOUSDT",
        "interval": "{{interval}}",
        "risk": 15.0,
        "commission": 0.1,
        "leverage": 1,
        "demo": {{demoMode}}
    },
    {
        "symbol": "LTCUSDT",
        "interval": "{{interval}}",
        "risk": 15.0,
        "commission": 0.1,
        "leverage": 1,
        "demo": {{demoMode}}
    },
    {
        "symbol": "ADAUSDT",
        "interval": "{{interval}}",
        "risk": 15.0,
        "commission": 0.1,
        "leverage": 1,
        "demo": {{demoMode}}
    },
    {
        "symbol": "XRPUSDT",
        "interval": "{{interval}}",
        "risk": 15.0,
        "commission": 0.1,
        "leverage": 1,
        "demo": {{demoMode}}
    },
    {
        "symbol": "EOSUSDT",
        "interval": "{{interval}}",
        "risk": 15.0,
        "commission": 0.1,
        "leverage": 1,
        "demo": {{demoMode}}
    },
    {
        "symbol": "XLMUSDT",
        "interval": "{{interval}}",
        "risk": 15.0,
        "commission": 0.1,
        "leverage": 1,
        "demo": {{demoMode}}
    },
    {
        "symbol": "TRXUSDT",
        "interval": "{{interval}}",
        "risk": 15.0,
        "commission": 0.1,
        "leverage": 1,
        "demo": {{demoMode}}
    },
    {
        "symbol": "QTUMUSDT",
        "interval": "{{interval}}",
        "risk": 15.0,
        "commission": 0.1,
        "leverage": 1,
        "demo": {{demoMode}}
    },
    {
        "symbol": "BTTUSDT",
        "interval": "{{interval}}",
        "risk": 15.0,
        "commission": 0.1,
        "leverage": 1,
        "demo": {{demoMode}}
    },
    {
        "symbol": "IOTAUSDT",
        "interval": "{{interval}}",
        "risk": 15.0,
        "commission": 0.1,
        "leverage": 1,
        "demo": {{demoMode}}
    },
    {
        "symbol": "ETCUSDT",
        "interval": "{{interval}}",
        "risk": 15.0,
        "commission": 0.1,
        "leverage": 1,
        "demo": {{demoMode}}
    },
    {
        "symbol": "ONTUSDT",
        "interval": "{{interval}}",
        "risk": 15.0,
        "commission": 0.1,
        "leverage": 1,
        "demo": {{demoMode}}
    },
    {
        "symbol": "ONEUSDT",
        "interval": "{{interval}}",
        "risk": 15.0,
        "commission": 0.1,
        "leverage": 1,
        "demo": {{demoMode}}
    }
]

###

GET http://{{host}}/watchdog/{{symbol}}/1h HTTP/1.1
Authorization: Bearer {{token}}

###

GET http://{{host}}/watchdog/{{symbol}}/1h/analysis HTTP/1.1
Authorization: Bearer {{token}}

###

GET http://{{host}}/watchdogs/analysis HTTP/1.1
Authorization: Bearer {{token}}
